### PR TITLE
Remove standalone uperf serviceip test

### PR DESCRIPTION
**Pull request by smalleni**
We can remove this as the serviceip test is now a part of test_uperf.sh

Signed-off-by: Sai Sindhur Malleni <smalleni@redhat.com>

### CODE REVIEW

**Comment by smalleni** [comment]
It seems logical for this test to fail, as the commit removes the test :)

**Review by jtaleric — APPROVED** [review]
LGTM

**Review by dry923 — APPROVED** [review]
LGTM!

**Pull request merged**
