### PR TITLE
BYOWL: Suppot for any options under spec and container

### PR DESCRIPTION
**Pull request by asispatra**
# Description
Currently BYOWL does not allow to run POD in privileged mode, hostPath access, mountPath, etc properties.

Can add support for these and all possible properties in BYOWL, so that we can use BYOWL for any workload which can run in privileged mode and should have access to hostPath etc.

Currently I have hard coded these option in the roles/byowl/templates/workload.yml and building the benchmark-operator myself.

If we add all possible properties support in BYOWL, individual do not need to build the benchmark-operator themselves.

This PR for issue #533

This generic changes does not work for all the options. May be I am missing something.
Detailed discussion: https://github.com/cloud-bulldozer/benchmark-operator/issues/533#issuecomment-799143133

### CODE REVIEW

**Comment by asispatra** [comment]
Has anyone verified this PR?

**Comment by rsevilla87** [comment]
Hey @asispatra, mind you update BYOL docs with these new options? specoptions and containeroptions?

**Comment by asispatra** [comment]
@rsevilla87, I will update the BYOWL document ASAP.

Thanks.

**Comment by asispatra** [comment]
Hi @rsevilla87, could you take a look into  https://github.com/cloud-bulldozer/benchmark-operator/issues/533#issuecomment-799143133 ?

**Review by jtaleric — APPROVED** [review]
LGTM!

**Comment by jtaleric** [comment]
> Hey @asispatra, mind you update BYOL docs with these new options? specoptions and containeroptions?

Can you add this @asispatra before we merge?

**Comment by asispatra** [comment]
Hi @jtaleric and @rsevilla87 ,

I have added the document for `specoptions` and `containeroptions`. Please review the doc changes.

**But, before you do any merge please review this** https://github.com/cloud-bulldozer/benchmark-operator/issues/533#issuecomment-799143133

Snap from the comment:
```apiVersion: ripsaw.cloudbulldozer.io/v1alpha1
kind: Benchmark
metadata:
  name: byowl-benchmark-example
  namespace: my-ripsaw
spec:
  workload:
    name: byowl
    args:
      image: "XXXXXX"
      clients: 1
      commands: 'COMMAND'
      specoptions:
        serviceAccountName: benchmark-operator      # <<<< Does Not work
        serviceAccount: benchmark-operator          # <<<< Does Not work
        volumes:                                    # <<<< Does Not work
        - name: test-volume
          hostPath:
            path: '/sys/fs/XXXXXX'
            type: Directory
      containeroptions:
        securityContext:                            # <<<< Does Not work
          privileged: true
        volumeMounts:                               # <<<< Does Not work
          - mountPath: '/sys/fs/XXXXXX'
            name: test-volume
        resources:                                  # <<<< This works
          requests:
            cpu: 4000m
          limits:
            cpu: 4000m
```


In case, these option already holds some value, the template not able to merge/combine new values with the existing value.

I think that we need some more changes to make it working.
It would be great if someone take a look deeply. 

Thanks.

**Comment by asispatra** [comment]
@jtaleric, Do we need any addition changes to get it merged?

**Comment by rsevilla87** [comment]
Hi @asispatra, I'd like to verify if https://github.com/cloud-bulldozer/benchmark-operator/pull/552 fixes some of the issues you're having before merging this one.

**Comment by rsevilla87** [comment]
@asispatra , #552 was already merged, can you verify if some of the issues you had were fixed?

**Comment by asispatra** [comment]
Hi @rsevilla87,

I have tried these changes with #552 . If I include `serviceAccountName, serviceAccount and securityContext` in the `specoptions` and `containeroptions`, I did not notice any changes compare to earlier result. But this time I had tried to include `serviceAccountName, serviceAccount and securityContext` in the `metadata` section and getting the following error on benchmark-operator's ansible log:
```
TASK [byowl : Start byowl job] *************************************************^M
^[[1;30mtask path: /opt/ansible/roles/byowl/tasks/main.yml:31^[[0m
^[[0;34mlooking for "workload.yml" at "/opt/ansible/roles/byowl/templates/workload.yml"^[[0m
^[[0;34mFile lookup using /opt/ansible/roles/byowl/templates/workload.yml as file^[[0m
^[[0;31mfatal: [localhost]: FAILED! => {^[[0m^M
^[[0;31m    "msg": "The task includes an option with an undefined variable. The error was: 'elasticsearch' is undefined\n\nThe error appears to be in '/opt/ansible/roles/byowl/tasks/main.yml': line 31, column 5, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n  - name: Start byowl job\n    ^ here\n"^[[0m^M
^[[0;31m}^[[0m
```

### This is how I have tried -
https://github.com/cloud-bulldozer/benchmark-operator/issues/533#issuecomment-806523890 you mentioned:
```
serviceAccountName, serviceAccount and securityContext are already defined in the template metadata.yml.j2
```
So currently BYOWL CRD looks like below:
```
apiVersion: ripsaw.cloudbulldozer.io/v1alpha1
kind: Benchmark
metadata:
  name: byowl-benchmark-example
  namespace: my-ripsaw
spec:
  metadata:
    collection: true
    targeted: true
    serviceaccount: benchmark-operator
    privileged: true
  workload:
    name: byowl
    args:
      image: "quay.io/asipatra/benchmarks:mmtests_x86"
      clients: 1
      specoptions:
        volumes:
        - name: hostpath-privileged
          hostPath:
            path: '/sys/fs/cgroup/memory'
            type: Directory
      containeroptions:
        volumeMounts:
        - mountPath: '/sys/fs/cgroup/memory'
          name: hostpath-privileged
        resources:
          requests:
            cpu: 4000m
          limits:
            cpu: 4000m
      commands:
        sleep infinity
```
Is there anything I am missing here?

**Comment by asispatra** [comment]
@rsevilla87 Any comment?

**Comment by rsevilla87** [comment]
> @rsevilla87 Any comment?

Waiting for https://github.com/cloud-bulldozer/benchmark-operator/pull/559 to be merged to make the `snakeCaseParameters` parameter work.

**Review by jtaleric — APPROVED** [review]
LGTM

**Comment by asispatra** [comment]
Thanks @jtaleric and @rsevilla87 ,

After https://github.com/cloud-bulldozer/benchmark-operator/pull/559 merged, these changes works fine. I have verified too.

**Pull request merged**
