### PR TITLE
add proxy to k8s client if it exists in env

### PR DESCRIPTION
**Pull request by qiliRedHat**
### Description
If http_proxy is in ENV, add proxy and proxy_headers to kubernetes.client.
example of the ENV variable:
http_proxy=http://<user>:<password>@<proxy_host>:<port>

### Fixes
https://github.com/cloud-bulldozer/benchmark-operator/issues/726

### CODE REVIEW

**Comment by mffiedler** [comment]
Tested with and without proxies.   Works as expected.

**Comment by mffiedler** [comment]
@mkarg75 @rsevilla87 Could you please assign this to someone for review?

**Comment by dry923** [comment]
@qiliRedHat Can you take a look at the CI failure please?

**Comment by qiliRedHat** [comment]
@dry923 Hi Russell It looks like a flaky download issue. Can I trigger a rerun of the test?

> Errors during downloading metadata for repository 'centos8-appstream-x86_64':
>   - Status code: 404 for http://mirror.centos.org/centos/8/AppStream/x86_64/os/repodata/repomd.xml (IP: 198.15.72.18)
> Error: Failed to download metadata for repo 'centos8-appstream-x86_64': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried
> Error: error building at STEP "RUN dnf install -y --nodocs redis openssl --enablerepo=centos8-appstream-* && dnf clean all": error while running runtime: exit status 1
> make: *** [Makefile:92: image-build] Error 125
> Error: Process completed with exit code 2.

**Comment by dry923** [comment]
@qiliRedHat Looks like you need to rebase. You are missing this commit that updated the repo links: https://github.com/cloud-bulldozer/benchmark-operator/commit/466ca91c9cf1a799b1ff90170c20119019d90670

**Comment by qiliRedHat** [comment]
@dry923 Thank you for the help, Russell. I've cherry picked this commit: https://github.com/cloud-bulldozer/benchmark-operator/commit/466ca91c9cf1a799b1ff90170c20119019d90670 and rebased.

**Comment by qiliRedHat** [comment]
@dry923 I saw some similar failures in the following tests as in my e2e testing but pr got merged. Are they known issues? 
https://github.com/cloud-bulldozer/benchmark-operator/runs/5275175163?check_suite_focus=true
https://github.com/cloud-bulldozer/benchmark-operator/runs/5140149779?check_suite_focus=true

**Comment by qiliRedHat** [comment]
@dry923 Would you help me to get the test passed? Where can I check the failed pod logs to know what's wrong here? Or is there some known issue? Thank you.

**Review by rsevilla87 — APPROVED** [review]
LGTM!

**Pull request merged**
