### PR TITLE
Added handling of fio bsrange parameter

### PR DESCRIPTION
**Pull request by acalhounRH**
In order to produce a non-uniform distribution test with fio, this PR attempts to add the use of fio's bsrange parameter. Essentially in this PR we check whether the user is using bs or bsrange, and then loops through the test as previous.

```
if bs in args.bs
   for bs in ags.bs
      do test
elif bsrange in args.bsrange
   for bsrange in ags.bsrange
      do test
```

### CODE REVIEW

**Comment by acalhounRH** [comment]
@dry923 @rsevilla87 @jtaleric

**Comment by acalhounRH** [comment]
@bengland2

**Comment by rsevilla87** [comment]
Hey @acalhounRH @bengland2  , I think this change is not necessary, as it's possible to get bsrange configured with the current code using global_overrides or job_params parameters. I've verified that bsrange has precedence over bs.

Using this job
```ini
[global]
bs=64K
direct=1
ioengine=psync
directory=/mnt/
runtime=10
time_based=1

[myjob]                                                                                                                                                                                                           
filename=fio.test
filesize=20M
rw=write
bsrange=1k-4k
```
Generates the following output:

```console
fio job.ini 
myjob: (g=0): rw=write, bs=(R) 1024B-4096B, (W) 1024B-4096B, (T) 1024B-4096B, ioengine=psync, iodepth=1                                                                                                                                       
fio-3.21
Starting 1 process
Jobs: 1 (f=1): [W(1)][100.0%][w=177MiB/s][w=36.4k IOPS][eta 00m:00s]
myjob: (groupid=0, jobs=1): err= 0: pid=3785829: Wed Aug 26 11:34:04 2020
  write: IOPS=35.9k, BW=175MiB/s (183MB/s)(1750MiB/10001msec); 0 zone resets
    slat (nsec): min=1616, max=3893.6k, avg=20480.50, stdev=19193.34
    clat (nsec): min=193, max=1857.6k, avg=6800.80, stdev=13293.23
     lat (usec): min=15, max=3897, avg=27.40, stdev=18.14
```

I also verified that fio is executing the workload correctly:

```console
$ sudo strace -s0 -e pwrite64  -f fio --thread job.ini
[pid 3788559] pwrite64(5, ""..., 3072, 7393280) = 3072
[pid 3788559] pwrite64(5, ""..., 3072, 7396352) = 3072
[pid 3788559] pwrite64(5, ""..., 3072, 7399424) = 3072
[pid 3788559] pwrite64(5, ""..., 4096, 7402496) = 4096
[pid 3788559] pwrite64(5, ""..., 2048, 7406592) = 2048
[pid 3788559] pwrite64(5, ""..., 3072, 7408640) = 3072
[pid 3788559] pwrite64(5, ""..., 4096, 7411712) = 4096
[pid 3788559] pwrite64(5, ""..., 4096, 7415808) = 4096
[pid 3788559] pwrite64(5, ""..., 3072, 7419904) = 3072
[pid 3788559] pwrite64(5, ""..., 4096, 7422976) = 4096
[pid 3788559] pwrite64(5, ""..., 1024, 7427072) = 1024
[pid 3788559] pwrite64(5, ""..., 4096, 7428096) = 4096
[pid 3788559] pwrite64(5, ""..., 4096, 7432192) = 4096
```

**Review by rsevilla87 — COMMENTED** [review]
^

**Comment by acalhounRH** [comment]
@bengland2 Ideally we want to run the same test, including all the permutations of samples, this means we have to duplicate the loops in each if-statement. If you are aware of how to do this without the duplicated code I would be interested in implementing that.

@rsevilla87 Yes, Fio will run bsrange over bs with override, unfortunately we then don't get the same looping structure and it creates a difficult issues of when parsing results with benchmark-wrapper.

**Comment by acalhounRH** [comment]
@bengland2 @rsevilla87 Based on conversations, I have update to reduce duplication by setting a loopvar and loopvar_str that are set to either bs or bsrange. please review.

**Comment by rsevilla87** [comment]
> @bengland2 @rsevilla87 Based on conversations, I have update to reduce duplication by setting a loopvar and loopvar_str that are set to either bs or bsrange. please review.

Thanks Alex, LGTM now. Mind you update documentation as well before merging?

**Comment by rsevilla87** [comment]
> > @bengland2 @rsevilla87 Based on conversations, I have update to reduce duplication by setting a loopvar and loopvar_str that are set to either bs or bsrange. please review.
> 
> Thanks Alex, LGTM now. Mind you update documentation as well before merging?

Hey Alex, can you take care of this?, As soon you update docs I'll merge this one :)

**Review by bengland2 — APPROVED** [review]
you eliminated the duplicate lines, am happy with it.

**Review by dry923 — APPROVED** [review]
LGTM!

**Review by rsevilla87 — APPROVED** [review]
LGTM!

**Pull request merged**
