### PR TITLE
try to remove all ripsaw state from K8S cluster before starting test

### PR DESCRIPTION
**Pull request by bengland2**
including security and CRD.
tested with smallfile CI on AWS EC2 cluster

### CODE REVIEW

**Comment by bengland2** [comment]
I was deleting the wrong CRD.   This needs to delete the CRD that references the UUID, and it can only be done at the end of a CI test, not at the beginning of the next one.  And in fact it is being done there in cleanup_resources.      Trying again by just deleting deploy/, not CRD.   Still an improvement IMO.

**Comment by bengland2** [comment]
pausing this because I'm concerned that deploy/4* are global, not namespace-local, so deleting in each test case could impact other concurrent CI runs in the same cluster.

**Comment by dry923** [comment]
> pausing this because I'm concerned that deploy/4* are global, not namespace-local, so deleting in each test case could impact other concurrent CI runs in the same cluster.

@bengland2 I took a look at the test.sh and I think you are right. We would need to add in some logic to tag benchmark-operator-kube with a -$UUID as well

**Comment by bengland2** [comment]
closing this for now.

**Pull request closed without merging**
