### PR TITLE
Able to run the sysbench test on a specific node

### LINKED ISSUE #661: sysbench node selector missing
**Describe the bug**
The readme file for the sysbench test doesn't explain how to specify a node, neither the sample file.

**To Reproduce**
1. Go to the sysbench readme
2. Look for how to run the test on a specific node

**Expected behavior**
A clear and concise description of how to specify the node you want to test, as well as the sample file containing all the parameters with some comments.

**Screenshots**

**Desktop (please complete the following information):**
Unrelated

**Smartphone (please complete the following information):**
Unrelated

**Additional context**

### PR DESCRIPTION
**Pull request by e-minguez**
### Description
Enable running the sysbench test on specific node specifying a `pin_node` parameter in the cr.

### Fixes
Close #661

### CODE REVIEW

**Review by smalleni — APPROVED** [review]

**Comment by e-minguez** [comment]
Previous version was wrong, force pushing a proper one, sorry.

**Comment by jtaleric** [comment]
@e-minguez can you add a quick update to the doc with the new option? https://github.com/cloud-bulldozer/benchmark-operator/blob/master/docs/sysbench.md#running-sysbench

**Comment by e-minguez** [comment]
> @e-minguez can you add a quick update to the doc with the new option? https://github.com/cloud-bulldozer/benchmark-operator/blob/master/docs/sysbench.md#running-sysbench

Done.

**Review by rsevilla87 — APPROVED** [review]
LGTM!

**Pull request merged**
