### PR TITLE
Add Iperf3 pod anti-affinity rules

### PR DESCRIPTION
**Pull request by martineg**
Add pod anti-affinity rules to place iperf3 client and server benchmark pods on different nodes

### CODE REVIEW

**Comment by jtaleric** [comment]
Do we want this by default? Or allow a switch to disable the affinity?

**Comment by martineg** [comment]
@jtaleric Added this on by default similar to what's already in the uperf workload (#238) - but a switch to disable might make sense.

**Review by rsevilla87 — APPROVED** [review]
LGTM

**Comment by jtaleric** [comment]
LGTM!

**Pull request merged**
