### PR TITLE
Add container granurality to metrics

### PR DESCRIPTION
**Pull request by rsevilla87**
### Description

We need more granularity in tests like node-density

Signed-off-by: Raul Sevilla <rsevilla@redhat.com>

### CODE REVIEW

**Review by mohit-sheth — APPROVED** [review]
LGTM

**Comment by dry923** [comment]
@rsevilla87 failed w/ 
```
./run_test.sh: line 25: roles/kube_burner/files/metrics.yaml.out: No such file or directory
```

**Pull request merged**
