### PR TITLE
zone affinity for uperf clients

### PR DESCRIPTION
**Pull request by mukrishn**
### Description
Pod affinity to keep server and client within same zone to avoid external variability.

### CODE REVIEW

**Review by jtaleric — COMMENTED** [review]
Since this is required during scheduling, if the AZ only has a single node, will the client ever launch?

**Comment by rsevilla87** [comment]
> Since this is required during scheduling, if the AZ only has a single node, will the client ever launch?

I think not since the policy is `requiredDuringSchedulingIgnoredDuringExecution`, I think we should add this policy as `preferredDuringSchedulingIgnoredDuringExecution`

**Comment by mukrishn** [comment]
This is keeping the server and client in the same zone, so why can't we enforce it by keeping `requiredDuring` instead of `preferredDuring` ? at all cases we will have a single zone isn't it.

**Comment by rsevilla87** [comment]
> This is keeping the server and client in the same zone, so why can't we enforce it by keeping `requiredDuring` instead of `preferredDuring` ? at all cases we will have a single zone isn't it.

In bare metal environments by default there's only one zone, for example

**Comment by mukrishn** [comment]
> In bare metal environments by default there's only one zone, for example

Yes so server and client will use the same zone in that case.

**Comment by jtaleric** [comment]
> > Since this is required during scheduling, if the AZ only has a single node, will the client ever launch?
> 
> I think not since the policy is `requiredDuringSchedulingIgnoredDuringExecution`, I think we should add this policy as `preferredDuringSchedulingIgnoredDuringExecution` to prevent single node on AZ test cases to fail

Yeah, I think we need to move to preferred vs required.

**Review by rsevilla87 — APPROVED** [review]
@smalleni oh, that's right!; somehow I thought the goal was to deploy the clients on different zones, makes sense now. LGTM

**Comment by mukrishn** [comment]
Note: With this affinity we need at least 2 nodes in a single zone. so [airflow](https://github.com/mukrishn/airflow-kubernetes/commit/d33146da177bdecd0c9c4ac217e0ba8a82fb9bde) worker counts have to be raised to 6.

**Comment by mukrishn** [comment]
@smalleni  just confirmed that baremetal nodes are not having this `topology.kubernetes.io/zone` label, so it might break BM runs. better to be `preferred` ?

**Comment by jtaleric** [comment]
> @smalleni just confirmed that baremetal nodes are not having this `topology.kubernetes.io/zone` label, so it might break BM runs. better to be `preferred` ?

Or we apply the label prior to execution... 

I ran into this running these scripts against non-ocp deployments too (EKS and GKE in particular).

**Comment by mukrishn** [comment]
> Or we apply the label prior to execution...

Not sure if adding labels would be an appropriate solution without knowing the placement of machines. Never played with zoning on baremetal node before, happy to investigate further if that is a way.

For time being lets make it `preferred` ?

**Comment by rsevilla87** [comment]
> > Or we apply the label prior to execution...
> 
> Not sure if adding labels would be an appropriate solution without knowing the placement of machines. Never played with zoning on baremetal node before, happy to investigate further if that is a way.
> 
> For time being lets make it `preferred` ?

makes sense to me

**Review by rsevilla87 — APPROVED** [review]
Ignoring FIO failures, lgtm!

**Pull request merged**
