### PR TITLE
Fio no log hist

### PR DESCRIPTION
**Pull request by bengland2**
do not merge yet, in process of running fio CI tests, but tested this on a small scale
This PR turns off histogram logging by default, while allowing the user to turn it back on for later development
This shrinks the amount of log data being fetched by fio-client pod, hopefully reducing chance of fio inflate error

### CODE REVIEW

**Comment by rsevilla87** [comment]
@bengland2 something weird happened during CI tests. fio client took a lot of time

```shell
[root@ip-172-31-40-110 ~]# oc logs  fio-client-5aec2453-v85vv  | wc -l
918162
```

**Comment by bengland2** [comment]
yeah I saw this running on my laptop, the final tests/test_crs/fiod_hostpath.yaml took almost a half-hour, so the CI timed it out:
```
11:39:02 + timeout -k 1200s 1200s bash -c 'wait_for_benchmark fiod-hostpath-benchmark Complete'
11:39:02 + echo 'Timeout exceeded for: fiod-hostpath-benchmark'
11:39:02 Timeout exceeded for: fiod-hostpath-benchmark
```

**Review by jtaleric — APPROVED** [review]
LGTM

**Review by whitleykeith — APPROVED** [review]

**Pull request merged**
