### PR TITLE
Make redis image a variable

### PR DESCRIPTION
**Pull request by fritchie**
This adds a new variable to values.yaml named redisImage.

Specifying a custom location for the image can be needed in secure
environments.

### CODE REVIEW

**Review by jtaleric — APPROVED** [review]
LGTM

**Comment by jtaleric** [comment]
@whitleykeith +1 ?

**Review by whitleykeith — APPROVED** [review]
Lgtm

**Comment by fritchie** [comment]
I made a small change to update the docs

**Review by jtaleric — APPROVED** [review]
LGTM on the docs!

**Pull request merged**
