### PR TITLE
supporting nodeSelector for byowl

### PR DESCRIPTION
**Pull request by whitleykeith**
Required to resolve https://github.com/cloud-bulldozer/e2e-benchmarking/issues/56

Changes:
* Added `nodeselector` field into the `spec.workload.args` block of the Benchmark CRD for byowl workloads. 
* Added a Makefile to make it easier to build the operator and deploy it to a local k8s cluster.

### CODE REVIEW

**Comment by jtaleric** [comment]
:D Nice... Might i recommend you break out the makefile into a new PR ;)

**Comment by whitleykeith** [comment]
@jtaleric I removed it :)

**Review by jtaleric — APPROVED** [review]
lgtm

**Review by dry923 — APPROVED** [review]
LGTM!

**Review by chaitanyaenr — APPROVED** [review]
LGTM

**Pull request merged**
