### PR TITLE
remove if from populate_test_list function

### PR DESCRIPTION
**Pull request by dry923**
### Description
This if statement is causing https://github.com/cloud-bulldozer/benchmark-operator/pull/627 to fail. Removing as it is unclear the purpose of it and it was not there pre-version upgrade.

### CODE REVIEW

**Review by whitleykeith — APPROVED** [review]
lgtm

**Comment by bengland2** [comment]
@dry923 @rsevilla87 looks good, want to try this with 627, is it ready to merge?

**Review by jtaleric — APPROVED** [review]
LGTM

**Review by rsevilla87 — APPROVED** [review]
LGTM

**Pull request merged**
