### PR TITLE
Hammerdb: add upgrade pip

### PR DESCRIPTION
**Pull request by ebattat**
### Description
Fix dependency issue by pip upgrade
### Fixes
ImportError: cannot import name 'PROTOCOL_TLS'

After adding 'pip3 install --upgrade pip;' issue was solved

Full error log
`Traceback (most recent call last):
  File "/usr/local/bin/run_snafu", line 33, in <module>
    sys.exit(load_entry_point('snafu==0.0.1', 'console_scripts', 'run_snafu')())
  File "/usr/local/bin/run_snafu", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/local/lib/python3.6/site-packages/importlib_metadata/__init__.py", line 194, in load
    module = import_module(match.group('module'))
  File "/usr/lib64/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/lib/python3.6/site-packages/snafu/run_snafu.py", line 37, in <module>
    from snafu.utils.wrapper_factory import wrapper_factory
  File "/usr/local/lib/python3.6/site-packages/snafu/utils/wrapper_factory.py", line 10, in <module>
    from snafu.log_generator_wrapper.log_generator_wrapper import log_generator_wrapper
  File "/usr/local/lib/python3.6/site-packages/snafu/log_generator_wrapper/log_generator_wrapper.py", line 17, in <module>
    from .trigger_log_generator import Trigger_log_generator
  File "/usr/local/lib/python3.6/site-packages/snafu/log_generator_wrapper/trigger_log_generator.py", line 26, in <module>
    import boto3
  File "/usr/local/lib/python3.6/site-packages/boto3/__init__.py", line 16, in <module>
    from boto3.session import Session
  File "/usr/local/lib/python3.6/site-packages/boto3/session.py", line 17, in <module>
    import botocore.session
  File "/usr/local/lib/python3.6/site-packages/botocore/session.py", line 29, in <module>
    import botocore.credentials
  File "/usr/local/lib/python3.6/site-packages/botocore/credentials.py", line 34, in <module>
    from botocore.config import Config
  File "/usr/local/lib/python3.6/site-packages/botocore/config.py", line 16, in <module>
    from botocore.endpoint import DEFAULT_TIMEOUT, MAX_POOL_CONNECTIONS
  File "/usr/local/lib/python3.6/site-packages/botocore/endpoint.py", line 22, in <module>
    from botocore.awsrequest import create_request_object
  File "/usr/local/lib/python3.6/site-packages/botocore/awsrequest.py", line 24, in <module>
    import botocore.utils
  File "/usr/local/lib/python3.6/site-packages/botocore/utils.py", line 32, in <module>
    import botocore.httpsession
  File "/usr/local/lib/python3.6/site-packages/botocore/httpsession.py", line 10, in <module>
    from urllib3.util.ssl_ import (
ImportError: cannot import name 'PROTOCOL_TLS'`

### CODE REVIEW

**Review by jtaleric — CHANGES_REQUESTED** [review]
Are we positive we just want to blindly update pip?

**Comment by jtaleric** [comment]
cc @jeniferh

**Comment by ebattat** [comment]
@jtaleric, I have tested it locally and it solved the issue.

**Comment by jeniferh** [comment]
Yeah that resolved the import issue, I got the idea from the sysbench Dockerfile: https://github.com/cloud-bulldozer/benchmark-wrapper/blob/master/snafu/sysbench/Dockerfile#L9
I think it might be due to recent version bumps in the wrapper? The differences I saw after the pip upgrade:
`Successfully installed charset-normalizer-2.0.7 requests-2.26.0 urllib3-1.26.7`

**Review by amitsagtani97 — APPROVED** [review]
LGTM!

**Comment by jtaleric** [comment]
> Yeah that resolved the import issue, I got the idea from the sysbench Dockerfile: https://github.com/cloud-bulldozer/benchmark-wrapper/blob/master/snafu/sysbench/Dockerfile#L9 I think it might be due to recent version bumps in the wrapper? The differences I saw after the pip upgrade: `Successfully installed charset-normalizer-2.0.7 requests-2.26.0 urllib3-1.26.7`
> 
> Previous to the update we had urllib3-1.24.2 so I think that was the main problem.

ack 



> @jtaleric, I have tested it locally and it solved the issue.

ack - since this only impacts CNV happy to merge with this guidance.

**Pull request merged**
