### PR TITLE
Fix for issue 485 - uperf with multus not working

### PR DESCRIPTION
**Pull request by chinthagovardhan**
Fixes issue #485

### CODE REVIEW

**Comment by chinthagovardhan** [comment]
> Can one of the admins verify this patch?

Yes please.

**Comment by chinthagovardhan** [comment]
> Can one of the admins verify this patch?

ok to test

**Comment by chinthagovardhan** [comment]
ok to test

**Review by jtaleric — APPROVED** [review]
Good catch, thank you!

**Review by rsevilla87 — APPROVED** [review]
LGTM!, thanks, let's wait for CI test before merging

**Pull request merged**
