### PR TITLE
Update image location

### LINKED ISSUE #608: benchmark operator installation issue
**Describe the bug**
installation with 

```
git clone https://github.com/cloud-bulldozer/benchmark-operator.git
cd benchmark-operator
make deploy 
``` 
fails with 

```
$ oc get pods
NAME                                            READY   STATUS   RESTARTS   AGE
benchmark-controller-manager-847cb58bbb-tcwd9   1/2     Error    7          12m
```

```
$ oc logs  benchmark-controller-manager-847cb58bbb-tcwd9  -c manager
Error: unknown flag: --leader-elect
Usage:
  ansible-operator run [flags]

Flags:
      --ansible-args string                  Ansible args. Allows user to specify arbitrary arguments for ansible-based operators.
      --ansible-collections-path string      Path to installed Ansible Collections. If set, collections should be located in {{value}}/ansible_collections/. If unset, collections are assumed to be in ~/.ansible/collections or /usr/share/ansible/collections.
      --ansible-roles-path string            Ansible Roles Path. If unset, roles are assumed to be in {{CWD}}/roles.
      --ansible-verbosity int                Ansible verbosity. Overridden by environment variable. (default 2)
      --enable-leader-election               Enable leader election for controller manager. Enabling this will ensure there is only one active controller manager.
      --graceful-shutdown-timeout duration   The amount of time that will be spent waiting for runners to gracefully exit. (default 30s)
      --health-probe-bind-address string     The address the probe endpoint binds to. (default ":6789")
  -h, --help                                 help for run
      --inject-owner-ref                     The ansible operator will inject owner references unless this flag is false (default true)
      --leader-election-id string            Name of the configmap that is used for holding the leader lock.
      --leader-election-namespace string     Namespace in which to create the leader election configmap for holding the leader lock (required if running locally with leader election enabled).
      --max-concurrent-reconciles int        Maximum number of concurrent reconciles for controllers. Overridden by environment variable. (default 16)
      --metrics-addr string                  The address the metric endpoint binds to (default ":8080")
      --reconcile-period duration            Default reconcile period for controllers (default 1m0s)
      --watches-file string                  Path to the watches file to use (default "./watches.yaml")
      --zap-devel                            Development Mode defaults(encoder=consoleEncoder,logLevel=Debug,stackTraceLevel=Warn). Production Mode defaults(encoder=jsonEncoder,logLevel=Info,stackTraceLevel=Error)
      --zap-encoder encoder                  Zap log encoding (one of 'json' or 'console')
      --zap-log-level level                  Zap Level to configure the verbosity of logging. Can be one of 'debug', 'info', 'error', or any integer value > 0 which corresponds to custom debug levels of increasing verbosity
      --zap-stacktrace-level level           Zap Level at and above which stacktraces are captured (one of 'info', 'error', 'panic').

2021/07/19 09:57:32 unknown flag: --leader-elect
```

### PR DESCRIPTION
**Pull request by rsevilla87**
Signed-off-by: Raul Sevilla <rsevilla@redhat.com>

### Description
Let's use the cloud-bulldozer org!

### Fixes

Fixes #608

### CODE REVIEW

**Review by jtaleric — CHANGES_REQUESTED** [review]
https://github.com/operator-framework/community-operators/blob/master/community-operators/ripsaw/0.1.0/ripsaw.v0.1.0.clusterserviceversion.yaml#L84

We will need to get this updated too...

**Comment by dry923** [comment]
@rsevilla87 we'll need one for snafu too to update the default location in https://github.com/cloud-bulldozer/benchmark-wrapper/blob/master/ci/common.sh

**Comment by rsevilla87** [comment]
> @rsevilla87 we'll need one for snafu too to update the default location in https://github.com/cloud-bulldozer/benchmark-wrapper/blob/master/ci/common.sh

Snafu CI is currently pinned to the v0.1 tag https://github.com/cloud-bulldozer/benchmark-wrapper/blob/d64c991935324f636a5a6d3a134d8fff94737b85/ci/run_ci.sh#L20

**Comment by rsevilla87** [comment]
Fixed by https://github.com/cloud-bulldozer/benchmark-operator/pull/613

**Pull request closed without merging**
