### PR TITLE
Container build mechanism

### PR DESCRIPTION
**Pull request by rsevilla87**
### Description

Mechanism based on github actions pipelines to build  benchmark-operator containers for different architectures such as amd64, arm64 and ppc64le:

It leverages github actions to trigger a container build in these conditions:
-  When a new commit is added to the master branch. Builds and pushes containers for different hw architectures to `quay.io/cloud-bulldozer/benchmark-operator:latest-{amd64,arm64,ppc64le}`
- When a new tag is created.  Builds and pushes containers for different hw architectures to `quay.io/cloud-bulldozer/benchmark-operator:${TAG_NAME}-{amd64,arm64,ppc64le}`

Apart from building these containers images when the events above happen, it creates and updates a container manifest that is pushed to `quay.io/cloud-bulldozer/benchmark-operator:latest` and  `quay.io/cloud-bulldozer/benchmark-operator:${TAG_NAME}` respectively (Depending if a new commit is added to master or a new tag is created). Thanks to this container manifest, deploying benchmark-operator in different architectures would be transparent to the user as he could use the :latest or :${TAG_NAME} container image tags to deploy the operator.

I already have done some tests, you can find them here -> https://quay.io/repository/cloud-bulldozer/benchmark-operator?tab=tags

Fixes: #608

### CODE REVIEW

**Review by whitleykeith — APPROVED** [review]
lgtm

**Review by learnitall — APPROVED** [review]
LGTM

**Review by jtaleric — APPROVED** [review]
LGTM -- I am bummed out that `runs-on` doesn't work with centos.

**Review by jtaleric — APPROVED** [review]
new changes LGTM, thanks!

**Pull request merged**
