### PR TITLE
Disable snake_case conversion

### PR DESCRIPTION
**Pull request by rsevilla87**
### Description
Effort to disable automatic snake_case conversion in operator-sdk. Reference https://sdk.operatorframework.io/docs/building-operators/ansible/reference/watches/

### Fixes
Can help fixing the issues found at https://github.com/cloud-bulldozer/benchmark-operator/issues/533

Signed-off-by: Raul Sevilla <rsevilla@redhat.com>

### CODE REVIEW

**Comment by rsevilla87** [comment]
Seems like uperf CI is flaky when executing together with other tests.

**Review by whitleykeith — APPROVED** [review]
Lgtm

**Review by dry923 — APPROVED** [review]
LGTM!

**Review by jtaleric — APPROVED** [review]
LGTM

**Pull request merged**
